### ISSUE TITLE
Bad path error for MathJax

### ISSUE THREAD

**Issue by geauxdojang** [ocefpaf/python4oceanographers_intro_course#7]
@ocefpaf : I got following error when trying to serve the `mkdocs`. Any help? Thanks.

`Bad Path: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML`

**Comment by ocefpaf** [comment]
I don't recall if I ever needed Mathjax here but I believe it is add automatically via mkdocs configuration.
I guess you should update your mkdocs version and, if that does not work, open an issue upstream.

See https://github.com/mkdocs/mkdocs/issues/253 for a possible solution

PS: this page is quite old and built as a 1-time thing.

**Comment by geauxdojang** [comment]
Thanks.
